### ISSUE TITLE
Rerunning the program re-downloads the content

### ISSUE THREAD

**Issue by banjobbw** [qwoplakjos/TelegramMediaDownloader#1]
Hi 

If I rerun the program on the same TG channel, already downloaded videos are donloaded again.
Is it possible to skip already downloaded videos?

**Comment by banjobbw** [comment]
@qwoplakjos Could you please help?

**Comment by qwoplakjos** [comment]
Intended feature. Added "Skip already downloaded files" in a new relase. Please download it.
